name: doctor_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #A build system for Dart code generation and modular compilation
  build_runner: ^2.4.11
  # State management
  flutter_bloc: ^8.1.6
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  # for dependency injection
  get_it: ^7.7.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  # Networking
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.2
  pretty_dio_logger: ^1.4.0
  # localization
  intl: ^0.19.0
  easy_localization: ^3.0.7
  # for splash screen
  flutter_native_splash: ^2.4.1
  # An SVG rendering and widget library for Flutter, which allows painting
  flutter_svg: ^2.0.10+1
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.3
#  firebase_core: ^2.27.0
  # Flutter library to load and cache network images.
  cached_network_image: ^3.4.0
  # reading and writing simple key-value pairs
  shared_preferences: ^2.3.1
  # provides API to store data in secure storage.
#  flutter_secure_storage: ^9.2.2
  # easy way to add shimmer effect
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # assets:
  assets:
    - assets/svgs/
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
